services:
  redis:
    image: redis
    container_name: redis_container
    restart: always
    volumes:
      - redis_volume:/data/
    networks:
      - my_network

  network_parser:
    container_name: network_parser_container
    restart: always
    depends_on:
      - redis
    build:
      context: ../
      dockerfile: ./parser_infra/Dockerfile
    image: network_parser_image
    command: >
      sh -c "cd netparser
      && python3 manage.py makemigrations --settings=netparser.settings.prod 
      && python3 manage.py migrate --settings=netparser.settings.prod 
      && python3 manage.py auto_createsuperuser --settings=netparser.settings.prod 
      && python3 manage.py auto_creategroups --settings=netparser.settings.prod 
      && python3 manage.py collectstatic --no-input --settings=netparser.settings.prod
      && celery -A netparser worker --loglevel=info --detach
      && daphne --bind 0.0.0.0 --port 8003 --access-log=access.logs netparser.asgi:application
      "
    ports:
      - "8001:8003"
    networks:
      - my_network
    environment:
      POSTGRES_USER: scrapy_user
      POSTGRES_PASSWORD: scrapy_user_pass
      POSTGRES_DB: scrapy_db
    volumes:
      - static:/NetworkParser/netparser/collected_static/

  nginx:
    image: nginx:1.22.1
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
      - static:/staticfiles/
    ports:
      - 127.0.0.1:8000:80
    networks:
      - my_network
    depends_on:
      - network_parser

volumes:
  static:
  nginx_volume:
  redis_volume:

networks:
  my_network:
    external: true
