services:
  network_parser:
    container_name: network_parser_container
    restart: always
    build:
      context: ../
      dockerfile: ./parser_infra/Dockerfile
    image: network_parser_image
    command: >
      sh -c "cd netparser
      && python3 manage.py makemigrations --settings=netparser.settings.prod 
      && python3 manage.py migrate --settings=netparser.settings.prod 
      && python3 manage.py auto_createsuperuser --settings=netparser.settings.prod 
      && python3 manage.py collectstatic --no-input --settings=netparser.settings.prod"
    ports:
      - "8001:8003"
    volumes:
      - parser_volume:/NetworkParser/netparser/database/
      - static:/NetworkParser/netparser/collected_static/

  nginx:
    image: nginx:1.22.1
    restart: always
    volumes:
      - ./nginx:/etc/nginx/templates
      - static:/staticfiles/
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - network_parser

volumes:
  parser_volume:
  static:
  nginx_volume: